### PR TITLE
Remove tags from directory UI

### PR DESCRIPTION
**Pull request by Jake3231**
Per last week's team meeting, tags are going to be removed for the initial release. This PR simply removes the tags from the directory UI, but leaves them as shown in the org detail page to allow further design decisions to be made around the usage of tags there.
Screenshot 2022-12-06 at 12 08 58 PM

### CODE REVIEW

**Comment by Jake3231** [comment]
I realize this should probably also remove tags from the filter UI!

**Review by RubenOlano — APPROVED** [review]
Looks good 👍

**Review by Buchimi — APPROVED** [review]
I approve of removing tags.

I'm also yet to decide how to integrate them. 

Though they are unnecessary for a 1.0 release. 

But we should tackle this problem in a 1.x release

**Comment by Buchimi** [comment]
@Jake3231 

You can make the merge

**Comment by Jake3231** [comment]
> I approve of removing tags.
> 
> I'm also yet to decide how to integrate them.
> 
> Though they are unnecessary for a 1.0 release.
> 
> But we should tackle this problem in a 1.x release

Yeah, It would be great to consider this for a later release!

**Pull request merged**
