### PR TITLE
Added "Explore" placeholder link to navbar

### PR DESCRIPTION
**Pull request by Master7130**
Fixes issue #33

### CODE REVIEW

**Review by Jake3231 — APPROVED** [review]
Looks good!

We may want to later consider from a design perspective what the correct alignment should be for the Explore button and the logo text.

**Comment by Master7130** [comment]
> Looks good!
> 
> We may want to later consider from a design perspective what the correct alignment should be for the Explore button and the logo text.

Are you referring to how the logo text and the Explore button are slightly misaligned?
image

**Comment by Jake3231** [comment]
Yes. This change does follow the expected design according to current spec, though we may want to consider changes to make this appear more aligned.

cc @Hanneisuru

**Comment by Master7130** [comment]
> Yes. This change does follow the expected design according to current spec, though we may want to consider changes to make this appear more aligned.

Ok, I'll take a look at how I can fix that.

**Pull request merged**
