### PR TITLE
Add MIT License to repo

### PR DESCRIPTION
**Pull request by Jake3231**
This PR adds the MIT license to the Jupiter repository. The MIT license establishes very permissive guidelines around usage of this repo, requiring only a copyright attribution and notice when this repo is used.

I am requesting review from those who have contributed to this repository, as well as pinging specific contributors here. Please review the `LICENSE.md` file to see the full details of the new license. By approving this PR or replying affirmatively in the discussion, you are confirming that you agree that this repository, including your contributions, may be licensed as described in the `LICENSE.md` file.

### CODE REVIEW

**Comment by Jake3231** [comment]
@Vinitvh @ujwalkumar1995 @gxanine Please reply to this discussion indicating whether you agree that your contributions to this repository may be licensed under the MIT license, as detailed in the `LICENSE.md` file in this PR.

**Comment by ujwalkumar1995** [comment]
@Jake3231 
Acknowledged!

**Comment by Jake3231** [comment]
> @Jake3231
> Acknowledged!

Thanks! Just to confirm, does that indicate that you're okay with your contributions being licensed under the MIT license?

**Comment by gxanine** [comment]
Of course! I certainly agree :)

**Comment by Vinitvh** [comment]
I agree.

**Comment by ujwalkumar1995** [comment]
Yes @Jake3231 
I agree!

**Review by felixjimenez4 — APPROVED** [review]
LGTM
I understand I am agreeing to the MIT license

**Review by RubenOlano — APPROVED** [review]

**Review by WillieCubed — APPROVED** [review]
Looks good to me! I consent to adopting the MIT license.

**Review by shreyon312 — COMMENTED** [review]
I approve this

**Comment by Master7130** [comment]
I agree

**Comment by Jake3231** [comment]
Merging this now, as all contributors have agreed to adopt the MIT license, either through review of the PR or through the discussion.

**Pull request merged**
