### PR TITLE
71 image loading

### PR DESCRIPTION
**Pull request by RubenOlano**
Need someone to test if this solution works better. Should be a bit faster with the priority tag

### CODE REVIEW

**Comment by Jake3231** [comment]
In a quick test I saw better performance, though I'd have to test it more extensively.

**Comment by Jake3231** [comment]
Hopefully eventually we can set up automated testing for some stuff like that

**Comment by Jake3231** [comment]
If we can resolve the Vercel issue, that may be helpful to verify the fix, though if not it may be helpful for multiple people to test if this is speeding up image loading. At least when I briefly tested it seemed to be better.

**Review by Jake3231 — DISMISSED** [review]
Tentatively approving this, as it seems to help and I don't see any big potential downsides to this change, and we can trivially change it if further testing warrants.

**Comment by RubenOlano** [comment]
Looks a lot better to me now

**Review by Jake3231 — APPROVED** [review]
LGTM! With the further changes it's even faster!

**Pull request merged**
