### PR TITLE
Update directory and events page

### LINKED ISSUE #84: Consider changing standard alignment of page titles
# Overview

During the review of #68, discussion was brought up about changing the standard alignment of page titles used in Jupiter (currently in Events and Directory). This issue is tracking the discussion/work to potentially change the title alignment.

## Supplementary Information
Currently the titles look like this:

Screenshot 2022-10-31 at 7 27 42 PM
("Organization Directory" in this image)

### PR DESCRIPTION
**Pull request by RubenOlano**
Closes #84. Let me know if it needs more fixing

### CODE REVIEW

**Comment by Jake3231** [comment]
Screenshot 2022-11-01 at 1 11 33 PM

Is it expected for the text to be on two lines with this change?

**Comment by RubenOlano** [comment]
@Jake3231 
Fixed, sorry about that

**Review by Jake3231 — APPROVED** [review]
These changes look good!

**Comment by Jake3231** [comment]
Was previously holding to confirm we want to move forward with the design change, though this is looking pretty good!

**Pull request merged**
