### PR TITLE
Added events pages title and search bar

### LINKED ISSUE #61: Create search bar and page title
Add a search bar and page title to the Events page

### PR DESCRIPTION
**Pull request by Master7130**
Resolves #61

### CODE REVIEW

**Comment by Jake3231** [comment]
Thanks for making that change! Looks like this was also addressed in #68. I'll take a look at if we can merge these two changes together.

**Comment by Jake3231** [comment]
As #68 addresses this, as well as additional UI, it might make the most sense to move forward with #68. @Master7130 I have requested your review of that PR, if you are able to take a look at that also.

**Comment by Master7130** [comment]
> As #68 addresses this, as well as additional UI, it might make the most sense to move forward with #68. @Master7130 I have requested your review of that PR, if you are able to take a look at that also.

Sure I'll take a look at it.

**Comment by Jake3231** [comment]
Thanks again for making this change. Currently closing as this was included in #68 .

**Pull request closed without merging**
