### PR TITLE
Create a sample 'about' page

### PR DESCRIPTION
**Pull request by gilnicki**
Fixes https://github.com/UTDNebula/jupiter/issues/20

### CODE REVIEW

**Comment by Buchimi** [comment]
When i try building the app, i get this error
`Could not find a declaration file for module 'react-simple-flex-grid'`.

**Comment by Jake3231** [comment]
I'm not seeing an issue at build time with this change

**Comment by gilnicki** [comment]
@Buchimi 
> When i try building the app, i get this error `Could not find a declaration file for module 'react-simple-flex-grid'`.

Does this message come up for you only on my branch? 
Seems unlikely that my changes would cause such error, as all I have added is a simple functional componenent with no special dependencies.

**Comment by Jake3231** [comment]
I did just recently see an instance where a related warning comes up, though the app seems to still build/run as expected on my end. As a troubleshooting step, does `npm i react-simple-flex-grid` resolve the issue?

**Comment by Jake3231** [comment]
Tracking issues here: https://github.com/UTDNebula/jupiter/issues/31

**Comment by Jake3231** [comment]
@gilnicki Please request review when the code is ready to be reviewed for inclusion in the repo. The mentioned issues should be fixed now.

**Comment by gilnicki** [comment]
> @gilnicki Please request review when the code is ready to be reviewed for inclusion in the repo. The mentioned issues should be fixed now.

Hi @Jake3231, I can't request a review - Usually there's a button or a list of reviewers near the `Reviewers` section on the right of a thread but it's not there this time:
image

**Comment by gilnicki** [comment]
Also, I'm not sure if it's alright to have the about page like this, but I reckon it's fine to have the 'template' for now and then fill in the actual contents with another PR.

**Review by Jake3231 — APPROVED** [review]
Looks good! Approving as #31 was resolved.

**Pull request merged**
