### PR TITLE
JUP-52-make-carousel-bigger

### PR DESCRIPTION
**Pull request by ishaanthenerd**

### CODE REVIEW

**Review by RubenOlano — DISMISSED** [review]
Looks good 👍🏽

**Comment by nl32** [comment]
I mean it looks good but I can't tell a difference between this pr and dev. I feel like there was some design specific change that was wanted but I don't remember what exactly.

**Comment by nl32** [comment]
I think it was that Solomon wanted the carousel to fill the whole space horizontally, cause currently if you widen the page enough there is additional white space, @RubenOlano correct me if I'm wrong.

**Comment by ishaanthenerd** [comment]
Yep, that's what Solomon told me.

**Review by nl32 — CHANGES_REQUESTED** [review]
in that case i'm still seeing the issue, there still seems to be white space on the deployment. Ideally it would be the same width as the tag section, which should be as wide as the whole container.

Screenshot 2024-04-01 at 6 27 59 PM

**Review by nl32 — APPROVED** [review]
Wide Carousel! lgtm.

**Review by RubenOlano — APPROVED** [review]

**Pull request merged**
