### PR TITLE
Events Page

### PR DESCRIPTION
**Pull request by Master7130**
Created a dynamic route for an event details page. Can be accessed by clicking on the title of the event on the events page. 

#107

### CODE REVIEW

**Comment by Jake3231** [comment]
We should consider how this also could fit with #123

**Comment by Buchimi** [comment]
There's a way to do this with nextjs routing system. 

I imagine we'll need the backend to provide the data we need to create the page

**Comment by Jake3231** [comment]
@Master7130 Thanks again for making this change! Per the recent meetings, as it sounds like we'll be moving forward with the redesign branch, do you think this could be easily ported to that as well? We could merge a design into develop now, and add it back to the redesign later also.

**Comment by Master7130** [comment]
Yeah it shouldn't be too difficult to have something like this on the redesign branch. Would you like me to do it or will someone else handle it?

**Comment by Jake3231** [comment]
> Yeah it shouldn't be too difficult to have something like this on the redesign branch. Would you like me to do it or will someone else handle it?

If you are able to add that, that would be awesome. I'd suggest branching from `redesign`, and also checking with Solomon and Ruben regarding design and implementation details

**Pull request closed without merging**
