### PR TITLE
(JUP-12) Updated Contact Buttons and Minor fixes to Other Pages

### PR DESCRIPTION
**Pull request by KennethImphean**
CONTACT BUTTONS:
Contact Buttons were updated to adhere better to Design Team's Figma. Colors were also changed and icons are more distinguishable when hovered over by mouse.

MINOR FIXES:
Capitalization of the settings page for unsigned users was fixed.
About Page had redundant code dealing with max width removed.

### CODE REVIEW

**Comment by RubenOlano** [comment]
Run `npm run build` and fix the issues to be able to view the deploy. Some issues with eslint when build

**Comment by KennethImphean** [comment]
I ran npm run build and the issues were fixed

**Review by RubenOlano — DISMISSED** [review]
Looks good but we might want to move the object with svgs in a different file for clarity. I'll defer to the next review for the verdict though

**Review by nl32 — CHANGES_REQUESTED** [review]
changes to About and Settings look good. I do think it would probably be better to relocate the contact icon svgs into a new file. it looks a bit messy right now and would probably make more sense in a different file.

**Comment by KennethImphean** [comment]
I moved the object into a new file called ContactIcons.

**Review by nl32 — APPROVED** [review]
Looks good, may want to change the export name to something more descriptive though, or make it a default export.

**Review by RubenOlano — APPROVED** [review]

**Pull request merged**
