### PR TITLE
Events placeholder

### LINKED ISSUE #9: Create Events placeholder on homepage
Currently, the Homepage includes just the banner images with the title "Jupiter" and a tagline. There needs to be a list of recommended events below that, as included in the design spec:
Screen Shot 2022-04-20 at 10 42 23 PM

### PR DESCRIPTION
**Pull request by Master7130**
Created EventCard component and added it to the homepage as a placeholder for the events section

Resolves #9

### CODE REVIEW

**Review by Jake3231 — CHANGES_REQUESTED** [review]
That is looking pretty good! Looks like the last thing I needs is the "Events" title as shown in the Figma design:

Screenshot 2022-10-23 at 7 11 02 PM

**Comment by RubenOlano** [comment]
I would also switch to using the NextJS image component for consistency as it works well with the vercel deploy

**Comment by Master7130** [comment]
@RubenOlano I switched to NextJS Image but I'm having trouble resizing it. My code is in the image below. Right now the background fills up the whole screen. The image isn't being contained inside the div and just covers the whole screen. Any idea on how to fix this?

image

image

**Comment by RubenOlano** [comment]
image
Something along these lines, contain and fill will just fill up its parent container which I think is being set to the full screen.

**Comment by RubenOlano** [comment]
> @RubenOlano I switched to NextJS Image but I'm having trouble resizing it. My code is in the image below. Right now the background fills up the whole screen. The image isn't being contained inside the div and just covers the whole screen. Any idea on how to fix this?
> 
> image
> 
> image

image
You're gonna have to set the height/width manually. The `layout='fill'` and 'objectFit='contain'` makes it fill up it's parent component which is why its taking up the entire screen

**Pull request closed without merging**
