### PR TITLE
Added events page search bar and title

### LINKED ISSUE #61: Create search bar and page title
Add a search bar and page title to the Events page

### PR DESCRIPTION
**Pull request by Master7130**
Resolves #61

### CODE REVIEW

**Comment by Jake3231** [comment]
Thanks for making that change! It looks like this branch includes some older UI - do you know if this was branched from `develop`?

**Review by RubenOlano — CHANGES_REQUESTED** [review]
You may have to rebase the branch, some dependencies seem to be from an older branch

**Comment by Master7130** [comment]
> Thanks for making that change! It looks like this branch includes some older UI - do you know if this was branched from `develop`?

@Jake3231 @RubenOlano Yeah I totally forgot about that. It should be fixed now.

**Comment by Master7130** [comment]
I take back what I said earlier. There is something very wrong with my branch so I'm going to restart.

**Pull request closed without merging**
